// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwavwvmhhypsohnruvdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53YXZ3dm1oaHlwc29obnJ1dmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzMwNzgsImV4cCI6MjA1NTcwOTA3OH0.FmAIpZTeWIuAYEKLa0ZKjyj-gTtoat67Vq3wrEq4W1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);